### ISSUE TITLE
Background-image till "hittar du inte det du söker" har repeat på background repeat property, borde ha no repeat.

### ISSUE THREAD

**Issue by ThomasAxakon** [simpell-dev/simpell-www-bugs#68]
Startsida
Förbättring
Chrome

https://dl.airtable.com/.attachmentThumbnails/f21bc24a0a5445a4e4e1ea1e54ebda2e/429ff9f0

**Comment by PeterLAxakon** [comment]
bör vara åtgärdat i nästa release
